### ISSUE TITLE
Parsing de commandes

### ISSUE THREAD

**Issue by lmouret** [hackbordeaux/bot#2]
- Trouver outils existants
- Établir une liste de commandes et leurs arguments
`!aide` affiche l'aide générale
`!aide <cmd>` affiche la doc de la commande `cmd`
`!blague` sort une blague au hasard. Rajouter des arguments comme `toto`, `absurde`... pour avoir un type de blague ?
`!meteo <ville> [<pays>]` pour avoir la météo actuelle dans `ville` située en `pays`. Si pays non renseigné on cherche en France.

**Comment by Dumbeldor** [comment]
#3
